package com.ckwanted.ss;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2016-05-26T10:28:30.506+01:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
@WebService(targetNamespace = "http://ckwanted.com/ss", name = "SimpleService")
@XmlSeeAlso({ObjectFactory.class})
public interface SimpleService {

    @WebMethod(action = "http://ckwanted.com/ss/NewOperation")
    @RequestWrapper(localName = "eliminar", targetNamespace = "http://ckwanted.com/ss", className = "com.ckwanted.ss.Eliminar")
    @ResponseWrapper(localName = "eliminarResponse", targetNamespace = "http://ckwanted.com/ss", className = "com.ckwanted.ss.EliminarResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.lang.String eliminar(
        @WebParam(name = "in", targetNamespace = "")
        java.lang.String in
    );
}
