
package com.ckwanted.ss;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2016-05-26T10:28:30.542+01:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
 
public class SimpleService_P1_Server{

    protected SimpleService_P1_Server() throws java.lang.Exception {
    	System.out.println("Preparando el servidor ..."); 
        Object implementor = new p1Impl();
        String address = "http://localhost:8080/ss/p1";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new SimpleService_P1_Server();
        System.out.println("Servidor Iniciado ...");
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Servidor apagado ...");
        System.exit(0);
    }
}
