package com.ckwanted.ss;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2016-05-24T12:24:30.137+01:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
@WebService(targetNamespace = "http://ckwanted.com/ss", name = "SimpleService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SimpleService {

    @WebMethod(action = "http://ckwanted.com/ss/NewOperation")
    @WebResult(name = "eliminarResponse", targetNamespace = "http://ckwanted.com/ss", partName = "parameters")
    public EliminarResponseT concat(
        @WebParam(partName = "parameters", name = "eliminar", targetNamespace = "http://ckwanted.com/ss")
        EliminarT parameters
    );
}
